name: Run Python Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify Python version

    # Run your Python script
    - name: Run Python script
      run: |
        python app.py
